version: '3.9'
services:
  web:
    depends_on:
      - db
    build: 
      context: ./web
      dockerfile: Dockerfile
    environment:
      - PORT=8020
    env_file:
      -  web/.env
    ports:
      - "8001:8020"
    volumes:
      - ./staticfiles:/app/staticfiles/
    
    command: sh -c "chmod +x /app/config/migrate.sh && sh /app/config/migrate.sh && /app/config/entrypoint.sh"
    networks:
      app_net:  
        ipv4_address: 192.168.0.2

  db:
    image: postgres
    restart: always
    env_file:
      -  web/.env
    command: -p 5433
    ports:
      - "5433:5433"
    expose:
      - 5433
    volumes:
      - ./local/postgres_db:/var/lib/postgres_db/data/
    networks:
      app_net:  
        ipv4_address: 192.168.0.3


volumes:
  db:
  # staticfiles:

networks:
  app_net:  
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1