version: '3.9'
services:
  web:
    depends_on:
      - db
    build: 
      context: ./web
      dockerfile: Dockerfile
    environment:
      - PORT=8020
    env_file:
      -  web/.env
    links:
      - db:db
    ports:
      - "8001:8020"
    volumes:
      - ./staticfiles:/app/staticfiles/
    
    command: sh -c "chmod +x /app/config/migrate.sh && sh /app/config/migrate.sh && /app/config/entrypoint.sh"
    networks:
             - djangonetwork

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      -  web/.env
    command: -p 5432
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./local/postgres_db:/var/lib/postgres_db/data/
    networks:
             - djangonetwork

volumes:
  db:


networks:
      djangonetwork:
          driver: bridge