apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj-blog-k8s-web-deployment
  labels:
    app: dj-blog-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dj-blog-k8s-web-deployment
  template:
    metadata:
      labels:
        app: dj-blog-k8s-web-deployment
    spec:
      containers:
        - name: dj-blog-k8s-web
          image: registry.digitalocean.com/djblog-k8s/dj-blog-k8s-web:latest
          envFrom:
          - secretRef:
              name: django-k8s-web-prod-env
          env:
            - name: PORT
              value: "8002"
          ports:
            - containerPort: 8002
      imagePullSecrets:
        - name: registry-djblog-k8s

---
apiVersion: v1
kind: Service
metadata:
  name: dj-blog-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
  selector:
    app: dj-blog-k8s-web-deployment
